apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-replicaset
  labels:
    app: echo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo-container
        image: registry.cluster.wik.cloud/public/echo
